class DivineName {
  final int number;
  final String arabic;
  final String transliteration;
  final String meaning;
  const DivineName({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.meaning,
  });
}

const asmaUlHusna = <DivineName>[
  DivineName(number: 1, arabic: 'ٱلرَّحْمَٰنُ', transliteration: 'Ar-Rahman', meaning: 'The Most Compassionate'),
  DivineName(number: 2, arabic: 'ٱلرَّحِيمُ', transliteration: 'Ar-Raheem', meaning: 'The Most Merciful'),
  DivineName(number: 3, arabic: 'ٱلْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The King, The Sovereign'),
  DivineName(number: 4, arabic: 'ٱلْقُدُّوسُ', transliteration: 'Al-Quddus', meaning: 'The Most Holy'),
  DivineName(number: 5, arabic: 'ٱلسَّلَامُ', transliteration: 'As-Salam', meaning: 'The Source of Peace'),
  DivineName(number: 6, arabic: 'ٱلْمُؤْمِنُ', transliteration: 'Al-Mu\'min', meaning: 'The Guardian of Faith'),
  DivineName(number: 7, arabic: 'ٱلْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaning: 'The Protector'),
  DivineName(number: 8, arabic: 'ٱلْعَزِيزُ', transliteration: 'Al-Aziz', meaning: 'The Almighty'),
  DivineName(number: 9, arabic: 'ٱلْجَبَّارُ', transliteration: 'Al-Jabbar', meaning: 'The Compeller'),
  DivineName(number: 10, arabic: 'ٱلْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Majestic'),
  DivineName(number: 11, arabic: 'ٱلْخَالِقُ', transliteration: 'Al-Khaliq', meaning: 'The Creator'),
  DivineName(number: 12, arabic: 'ٱلْبَارِئُ', transliteration: 'Al-Bari\'', meaning: 'The Evolver'),
  DivineName(number: 13, arabic: 'ٱلْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaning: 'The Fashioner'),
  DivineName(number: 14, arabic: 'ٱلْغَفَّارُ', transliteration: 'Al-Ghaffar', meaning: 'The Great Forgiver'),
  DivineName(number: 15, arabic: 'ٱلْقَهَّارُ', transliteration: 'Al-Qahhar', meaning: 'The All-Prevailing'),
  DivineName(number: 16, arabic: 'ٱلْوَهَّابُ', transliteration: 'Al-Wahhab', meaning: 'The Bestower'),
  DivineName(number: 17, arabic: 'ٱلرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaning: 'The Provider'),
  DivineName(number: 18, arabic: 'ٱلْفَتَّاحُ', transliteration: 'Al-Fattah', meaning: 'The Opener'),
  DivineName(number: 19, arabic: 'ٱلْعَلِيمُ', transliteration: 'Al-Alim', meaning: 'The All-Knowing'),
  DivineName(number: 20, arabic: 'ٱلْقَابِضُ', transliteration: 'Al-Qabid', meaning: 'The Withholder'),
  DivineName(number: 21, arabic: 'ٱلْبَاسِطُ', transliteration: 'Al-Basit', meaning: 'The Extender'),
  DivineName(number: 22, arabic: 'ٱلْخَافِضُ', transliteration: 'Al-Khafid', meaning: 'The Abaser'),
  DivineName(number: 23, arabic: 'ٱلرَّافِعُ', transliteration: 'Ar-Rafi\'', meaning: 'The Exalter'),
  DivineName(number: 24, arabic: 'ٱلْمُعِزُّ', transliteration: 'Al-Mu\'izz', meaning: 'The Giver of Honor'),
  DivineName(number: 25, arabic: 'ٱلْمُذِلُّ', transliteration: 'Al-Mudhill', meaning: 'The Giver of Dishonor'),
  DivineName(number: 26, arabic: 'ٱلسَّمِيعُ', transliteration: 'As-Sami\'', meaning: 'The All-Hearing'),
  DivineName(number: 27, arabic: 'ٱلْبَصِيرُ', transliteration: 'Al-Basir', meaning: 'The All-Seeing'),
  DivineName(number: 28, arabic: 'ٱلْحَكَمُ', transliteration: 'Al-Hakam', meaning: 'The Judge'),
  DivineName(number: 29, arabic: 'ٱلْعَدْلُ', transliteration: 'Al-\'Adl', meaning: 'The Just'),
  DivineName(number: 30, arabic: 'ٱللَّطِيفُ', transliteration: 'Al-Latif', meaning: 'The Most Subtle'),
  DivineName(number: 31, arabic: 'ٱلْخَبِيرُ', transliteration: 'Al-Khabir', meaning: 'The All-Aware'),
  DivineName(number: 32, arabic: 'ٱلْحَلِيمُ', transliteration: 'Al-Halim', meaning: 'The Forbearing'),
  DivineName(number: 33, arabic: 'ٱلْعَظِيمُ', transliteration: 'Al-Azim', meaning: 'The Magnificent'),
  DivineName(number: 34, arabic: 'ٱلْغَفُورُ', transliteration: 'Al-Ghafur', meaning: 'The Oft-Forgiving'),
  DivineName(number: 35, arabic: 'ٱلشَّكُورُ', transliteration: 'Ash-Shakur', meaning: 'The Appreciative'),
  DivineName(number: 36, arabic: 'ٱلْعَلِيُّ', transliteration: 'Al-\'Ali', meaning: 'The Most High'),
  DivineName(number: 37, arabic: 'ٱلْكَبِيرُ', transliteration: 'Al-Kabir', meaning: 'The Most Great'),
  DivineName(number: 38, arabic: 'ٱلْحَفِيظُ', transliteration: 'Al-Hafiz', meaning: 'The Preserver'),
  DivineName(number: 39, arabic: 'ٱلْمُقِيتُ', transliteration: 'Al-Muqit', meaning: 'The Sustainer'),
  DivineName(number: 40, arabic: 'ٱلْحَسِيبُ', transliteration: 'Al-Hasib', meaning: 'The Reckoner'),
  DivineName(number: 41, arabic: 'ٱلْجَلِيلُ', transliteration: 'Al-Jalil', meaning: 'The Majestic'),
  DivineName(number: 42, arabic: 'ٱلْكَرِيمُ', transliteration: 'Al-Karim', meaning: 'The Most Generous'),
  DivineName(number: 43, arabic: 'ٱلرَّقِيبُ', transliteration: 'Ar-Raqib', meaning: 'The Watchful'),
  DivineName(number: 44, arabic: 'ٱلْمُجِيبُ', transliteration: 'Al-Mujib', meaning: 'The Responsive'),
  DivineName(number: 45, arabic: 'ٱلْوَاسِعُ', transliteration: 'Al-Wasi\'', meaning: 'The All-Encompassing'),
  DivineName(number: 46, arabic: 'ٱلْحَكِيمُ', transliteration: 'Al-Hakim', meaning: 'The All-Wise'),
  DivineName(number: 47, arabic: 'ٱلْوَدُودُ', transliteration: 'Al-Wadud', meaning: 'The Most Loving'),
  DivineName(number: 48, arabic: 'ٱلْمَجِيدُ', transliteration: 'Al-Majid', meaning: 'The Most Glorious'),
  DivineName(number: 49, arabic: 'ٱلْبَاعِثُ', transliteration: 'Al-Ba\'ith', meaning: 'The Resurrector'),
  DivineName(number: 50, arabic: 'ٱلشَّهِيدُ', transliteration: 'Ash-Shaheed', meaning: 'The Witness'),
  DivineName(number: 51, arabic: 'ٱلْحَقُّ', transliteration: 'Al-Haqq', meaning: 'The Truth'),
  DivineName(number: 52, arabic: 'ٱلْوَكِيلُ', transliteration: 'Al-Wakil', meaning: 'The Trustee'),
  DivineName(number: 53, arabic: 'ٱلْقَوِيُّ', transliteration: 'Al-Qawi', meaning: 'The Most Strong'),
  DivineName(number: 54, arabic: 'ٱلْمَتِينُ', transliteration: 'Al-Matin', meaning: 'The Firm'),
  DivineName(number: 55, arabic: 'ٱلْوَلِيُّ', transliteration: 'Al-Wali', meaning: 'The Protecting Friend'),
  DivineName(number: 56, arabic: 'ٱلْحَمِيدُ', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy'),
  DivineName(number: 57, arabic: 'ٱلْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The Counter'),
  DivineName(number: 58, arabic: 'ٱلْمُبْدِئُ', transliteration: 'Al-Mubdi\'', meaning: 'The Originator'),
  DivineName(number: 59, arabic: 'ٱلْمُعِيدُ', transliteration: 'Al-Mu\'id', meaning: 'The Restorer'),
  DivineName(number: 60, arabic: 'ٱلْمُحْيِي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life'),
  DivineName(number: 61, arabic: 'ٱلْمُمِيتُ', transliteration: 'Al-Mumit', meaning: 'The Bringer of Death'),
  DivineName(number: 62, arabic: 'ٱلْحَيُّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living'),
  DivineName(number: 63, arabic: 'ٱلْقَيُّومُ', transliteration: 'Al-Qayyum', meaning: 'The Self-Subsisting'),
  DivineName(number: 64, arabic: 'ٱلْوَاجِدُ', transliteration: 'Al-Wajid', meaning: 'The Finder'),
  DivineName(number: 65, arabic: 'ٱلْمَاجِدُ', transliteration: 'Al-Majid', meaning: 'The Noble'),
  DivineName(number: 66, arabic: 'ٱلْوَاحِدُ', transliteration: 'Al-Wahid', meaning: 'The One'),
  DivineName(number: 67, arabic: 'ٱلْأَحَدُ', transliteration: 'Al-Ahad', meaning: 'The Unique'),
  DivineName(number: 68, arabic: 'ٱلصَّمَدُ', transliteration: 'As-Samad', meaning: 'The Eternal Refuge'),
  DivineName(number: 69, arabic: 'ٱلْقَادِرُ', transliteration: 'Al-Qadir', meaning: 'The Able'),
  DivineName(number: 70, arabic: 'ٱلْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The Most Powerful'),
  DivineName(number: 71, arabic: 'ٱلْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter'),
  DivineName(number: 72, arabic: 'ٱلْمُؤَخِّرُ', transliteration: 'Al-Mu\'akhkhir', meaning: 'The Delayer'),
  DivineName(number: 73, arabic: 'ٱلْأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First'),
  DivineName(number: 74, arabic: 'ٱلْآخِرُ', transliteration: 'Al-Akhir', meaning: 'The Last'),
  DivineName(number: 75, arabic: 'ٱلظَّاهِرُ', transliteration: 'Az-Zahir', meaning: 'The Manifest'),
  DivineName(number: 76, arabic: 'ٱلْبَاطِنُ', transliteration: 'Al-Batin', meaning: 'The Hidden'),
  DivineName(number: 77, arabic: 'ٱلْوَالِي', transliteration: 'Al-Wali', meaning: 'The Governor'),
  DivineName(number: 78, arabic: 'ٱلْمُتَعَالِي', transliteration: 'Al-Muta\'ali', meaning: 'The Most Exalted'),
  DivineName(number: 79, arabic: 'ٱلْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of All Goodness'),
  DivineName(number: 80, arabic: 'ٱلتَّوَّابُ', transliteration: 'At-Tawwab', meaning: 'The Accepter of Repentance'),
  DivineName(number: 81, arabic: 'ٱلْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger'),
  DivineName(number: 82, arabic: 'ٱلْعَفُوُّ', transliteration: 'Al-\'Afuww', meaning: 'The Pardoner'),
  DivineName(number: 83, arabic: 'ٱلرَّؤُوفُ', transliteration: 'Ar-Ra\'uf', meaning: 'The Most Kind'),
  DivineName(number: 84, arabic: 'مَالِكُ ٱلْمُلْكِ', transliteration: 'Malik-ul-Mulk', meaning: 'Master of the Kingdom'),
  DivineName(number: 85, arabic: 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'Lord of Majesty and Honor'),
  DivineName(number: 86, arabic: 'ٱلْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Equitable'),
  DivineName(number: 87, arabic: 'ٱلْجَامِعُ', transliteration: 'Al-Jami\'', meaning: 'The Gatherer'),
  DivineName(number: 88, arabic: 'ٱلْغَنِيُّ', transliteration: 'Al-Ghani', meaning: 'The Self-Sufficient'),
  DivineName(number: 89, arabic: 'ٱلْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher'),
  DivineName(number: 90, arabic: 'ٱلْمَانِعُ', transliteration: 'Al-Mani\'', meaning: 'The Preventer'),
  DivineName(number: 91, arabic: 'ٱلضَّارُّ', transliteration: 'Ad-Darr', meaning: 'The Creator of Harm'),
  DivineName(number: 92, arabic: 'ٱلنَّافِعُ', transliteration: 'An-Nafi\'', meaning: 'The Benefactor'),
  DivineName(number: 93, arabic: 'ٱلنُّورُ', transliteration: 'An-Nur', meaning: 'The Light'),
  DivineName(number: 94, arabic: 'ٱلْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide'),
  DivineName(number: 95, arabic: 'ٱلْبَدِيعُ', transliteration: 'Al-Badi\'', meaning: 'The Originator'),
  DivineName(number: 96, arabic: 'ٱلْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Everlasting'),
  DivineName(number: 97, arabic: 'ٱلْوَارِثُ', transliteration: 'Al-Warith', meaning: 'The Inheritor'),
  DivineName(number: 98, arabic: 'ٱلرَّشِيدُ', transliteration: 'Ar-Rashid', meaning: 'The Guide to the Right Path'),
  DivineName(number: 99, arabic: 'ٱلصَّبُورُ', transliteration: 'As-Sabur', meaning: 'The Most Patient'),
];
